name: Compile LaTeX Document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Fonts
        run: |
          sudo apt-get update
          sudo apt-get install fonts-noto-cjk fonts-noto-cjk-extra

      - name: Install Tectonic
        run: curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net | sh

      - name: Compile Document
        run: ./tectonic main.tex

      - uses: actions/upload-artifact@v4
        with:
          name: cv.pdf
          path: ./main.pdf
